### ISSUE TITLE
Support for Cloudinary

### ISSUE THREAD

**Issue by jrock17** [FriendsOfFlarum/upload#108]
- flagrow/upload extension version: <0.5.7>
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: Core

---

Can we add support for Cloudinary uploads? I noticed the old plugin had that already.

Thanks!

**Comment by luceos** [comment]
Hi there and thank you for suggesting this upload adapter for fof/upload.

In order to keep this extension maintainable with the few number of people currently involved with it, we do not accept pull requests or feature requests for new upload adapters. The reason for this is that we would need to test the adapter on each upgrade of Flarum, plus whenever changes occur on this API of the upload service.

As a small team maintaining many extensions isn't always easy. That's why we try to reduce the workload by making clear choices on what we do and don't support .

The best option you have is to (have someone) create a completely new extension that registers the additional upload adapter. The maintenance of that extension is then dispersed away from our team. The best way to add your adapter is by listening to the [Collecting event](https://github.com/FriendsOfFlarum/upload/blob/master/src/Events/Adapter/Collecting.php) using the `Flarum\Extend\Event` extender.

If you have any questions about the implementation, feel free to open a discussion on the [dev tag on discuss](https://discuss.flarum.org/t/dev).

Thank you for your understanding.
