### ISSUE TITLE
Download error of large files

### ISSUE THREAD

**Issue by Stefan-Dressler** [FriendsOfFlarum/upload#122]
I uploaded a 200MB Video file. That worked perfect. But the download runns into an memory isssue. Why the download is consuming memory? Is this a known issue?

**Comment by luceos** [comment]
Do you have an exception trace? Check the `storage/logs/flarum.log`.

**Comment by Stef-Dan** [comment]
Yes. Flarum log is empty. But php log comes up with:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 205087159 bytes) in /some-path/vendor/guzzlehttp/psr7/src/Stream.php on line 94, referer: https://some-url.com/d/28-some-name/8

The allocated size is exact the size of the file I try to download. 

Flarum core 0.1.0-beta.7
EXT flagrow-upload 0.6.0
PHP 5.6.32 (will be updated)

**Comment by luceos** [comment]
Okay so php is configured to deny download streams of that size. You'd probably be helped by increasing your memory limit in your php.ini.

Closing as this is unrelated to this extension.

**Comment by Stef-Dan** [comment]
Ah ok, downloads with your extension are always limited to the memory limit of the server. So no large file support. Got it.

**Comment by luceos** [comment]
Maybe if you disable the proxy, did you have that on?

**Comment by Stef-Dan** [comment]
Hmm, I do not use a proxy. 

I have looked deeper into your extension. Very nice work by the way. I like your coding style. Very understandable and just how I know and like it form laravel projects. Thanks a lot for all your effort. I think flarum is one of the best forum software at the moment. I am looking forward to switching to flarum soon.

I had not enough time to analyze your extension completely, but I think the output to the browser is made by the Flysystem package. If the stream output to the browser would be done throw a while loop in small pieces there is no problem with the memory limit anymore.

Maybe this issue comes from PHP 5.6 usage. I hope I can test it with PHP 7.1 soon. Do you have this issue with our installation?

**Comment by luceos** [comment]
I'll most certainly look into this. I'm unsure whether flysystem is providing a stream.

**Comment by Stef-Dan** [comment]
Nice. Thanks a lot in advance.

**Comment by clarkwinkelmann** [comment]
I'm closing this issue as there has been no new activity. The minimum PHP version has since changed any many versions of Upload were released since. Feel free to re-open an issue if the problem still exists in the latest version.
