### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by genxstylez** [FriendsOfFlarum/upload#140]
Hi, Is there any plans for integrating Google Cloud Storage?

Or can anyone point me how to do it?

**Comment by luceos** [comment]
Can you point me to the documentation? If you're up for it you can try to write your own adapter.

**Comment by genxstylez** [comment]
https://github.com/Superbalist/flysystem-google-cloud-storage

**Comment by jadsonlourenco** [comment]
Well, I did something that worked to me for now, but I not will submit as PR because I don't know PHP.

https://github.com/jadsonlourenco/upload/tree/google-cloud-storage

Just config with:
**1. Project ID** [String] (Your Google Cloud project ID)
**2. Credentials file** [String] (ex: /path-to-secrect.json)
**3. Bucker name** [String]

**Comment by luceos** [comment]
Hi there and thank you for suggesting this upload adapter for fof/upload.

In order to keep this extension maintainable with the few number of people currently involved with it, we do not accept pull requests or feature requests for new upload adapters. The reason for this is that we would need to test the adapter on each upgrade of Flarum, plus whenever changes occur on this API of the upload service.

As a small team maintaining many extensions isn't always easy. That's why we try to reduce the workload by making clear choices on what we do and don't support .

The best option you have is to (have someone) create a completely new extension that registers the additional upload adapter. The maintenance of that extension is then dispersed away from our team. The best way to add your adapter is by listening to the [Collecting event](https://github.com/FriendsOfFlarum/upload/blob/master/src/Events/Adapter/Collecting.php) using the `Flarum\Extend\Event` extender.

If you have any questions about the implementation, feel free to open a discussion on the [dev tag on discuss](https://discuss.flarum.org/t/dev).

Thank you for your understanding.
