### ISSUE TITLE
Nextcloud Integration of FLARUM

### ISSUE THREAD

**Issue by mangotasche** [FriendsOfFlarum/upload#143]
- flagrow/upload extension version: <x.y.z>
- flarum version: 0.1.0-beta.6
- upload adapter causing issues: <eg local or imgur>
- mimetype configurations: <eg .* => local>

---

Feature request: A connector plugin for FLARUM to use it inside the Nextcloud environment (and the same user login).

A plugin for the predecessor of FLARUM - Esotalk - already exists:
https://github.com/mroi/nextcloud-esotalk

**Comment by demlak** [comment]
any chance of this?

**Comment by Wastus** [comment]
Would be great, I miss an easy to integrate forum in Nextcloud.

**Comment by demlak** [comment]
Maybe we could donate for it?

**Comment by KoljaL** [comment]
Where can we donate for it?

**Comment by clarkwinkelmann** [comment]
You could directly reach out to a developer. Most of the FoF members also take on private work.

A full integration with Nextcloud login and upload sounds like a big piece of work though. I'm not sure how a simple adapter could work ?

**Comment by grrog** [comment]
Just the Nextcloud connection would already be great to avoid users having to enter their login twice…

**Comment by luceos** [comment]
You could reach out to nextcloud as well. They seem to use Flysystem for their own software. If they'd be willing to build and maintain the Flysystem adapter for their own software, it would be simple to integrate it into this extension.

**Comment by luceos** [comment]
Hi there and thank you for suggesting this upload adapter for fof/upload.

In order to keep this extension maintainable with the few number of people currently involved with it, we do not accept pull requests or feature requests for new upload adapters. The reason for this is that we would need to test the adapter on each upgrade of Flarum, plus whenever changes occur on this API of the upload service.

As a small team maintaining many extensions isn't always easy. That's why we try to reduce the workload by making clear choices on what we do and don't support .

The best option you have is to (have someone) create a completely new extension that registers the additional upload adapter. The maintenance of that extension is then dispersed away from our team. The best way to add your adapter is by listening to the [Collecting event](https://github.com/FriendsOfFlarum/upload/blob/master/src/Events/Adapter/Collecting.php) using the `Flarum\Extend\Event` extender.

If you have any questions about the implementation, feel free to open a discussion on the [dev tag on discuss](https://discuss.flarum.org/t/dev).

Thank you for your understanding.
