### ISSUE TITLE
GitHub repo adapter

### ISSUE THREAD

**Issue by philipsc** [FriendsOfFlarum/upload#222]
I made this request in the Flarum community, but have not received a response.
https://discuss.flarum.org/d/4154-friendsofflarum-upload-the-intelligent-file-attachment-extension/1019
Hope the author can consider supporting GitHub storage.

https://github.com/yumusb/autoPicCdn

**Comment by clarkwinkelmann** [comment]
It will be very complicated for us to integrate a library that's not documented in English. But we can accept a PR if someone wants to help with it.

The first step in creating a new driver would be to write a Flysystem-compatible adapter for the upload method, which I don't think that package has.

**Comment by philipsc** [comment]
The project provides an api interface and can be used for PicGo's web-uploader. The API address is written as "http://yourname/up.php", and the POST parameters are filled in with "pic"

**Comment by clarkwinkelmann** [comment]
I'm keeping this open together with the other adapter suggestions.

If many people express an interest in it, we might consider implementing it. Otherwise we gladly accept PRs for less wanted adapters if the implementation doesn't over-complicate the existing extension.

I do have some concerns regarding whether GitHub would actually allow this. For a few images it might be fine but if the repo in which you store the attachments grows GitHub will likely want you to use something like [Git Large File Storage](https://git-lfs.github.com/) which is billed by the GB, and it probably isn't as cost efficient as other cloud storage methods.

**Comment by philipsc** [comment]
Can plugin users decide whether to use the same storage? For example, pictures are stored on GitHub, and other files are stored on local or cloud storage.

**Comment by LCinHK** [comment]
https://github.com/892768447/flarum-ext-github-upload

Here is a complete finished extension, which can be easily merged I guess?

**Comment by luceos** [comment]
Hi there and thank you for suggesting this upload adapter for fof/upload.

In order to keep this extension maintainable with the few number of people currently involved with it, we do not accept pull requests or feature requests for new upload adapters. The reason for this is that we would need to test the adapter on each upgrade of Flarum, plus whenever changes occur on this API of the upload service.

As a small team maintaining many extensions isn't always easy. That's why we try to reduce the workload by making clear choices on what we do and don't support .

The best option you have is to (have someone) create a completely new extension that registers the additional upload adapter. The maintenance of that extension is then dispersed away from our team. The best way to add your adapter is by listening to the [Collecting event](https://github.com/FriendsOfFlarum/upload/blob/master/src/Events/Adapter/Collecting.php) using the `Flarum\Extend\Event` extender.

If you have any questions about the implementation, feel free to open a discussion on the [dev tag on discuss](https://discuss.flarum.org/t/dev).

Thank you for your understanding.
