### ISSUE TITLE
Miss compatibility with Beta 14

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/upload#240]
Actually miss compatibility with Beta 14
https://discuss.flarum.org/d/25184-issues-on-upgrading/2
https://github.com/PeopleInside/Flarum_Beta14_Upgrade/issues/1

**Comment by luceos** [comment]
We are well aware that some extensions aren't up to date yet. Bumping them under our noses like this isn't really civil.

Please have patience for extensions to be slowly patched, provide funding so that we can dedicate paid hours to that through donating at https://opencollective.com/fof or provide a tested Pull Request for the upgrade of this extension.

Thank you for your understanding.

**Comment by PeopleInside** [comment]
Hi @luceos , how can I know when the extension is ready?
I see this as an issue and I open for know when is solve and be able to update, looks not bumping to me.
Sorry.

**Comment by luceos** [comment]
Follow the discussion on discuss, updates are announced there.
