### ISSUE TITLE
Text files cannot be previewed correctly

### ISSUE THREAD

**Issue by ianchb** [FriendsOfFlarum/upload#308]
### Text files cannot be previewed correctly
--------
I‘ve just updated the extension and tried to use the text preview template.
![image](https://user-images.githubusercontent.com/45872450/151180026-f6e828f6-36e1-43fa-ada2-81fbd37c9296.png)

--------

1. Then, I uploaded a long(>5 lines) .txt file but I didn't see "Expand/Collapse Preview" button.

![image](https://user-images.githubusercontent.com/45872450/151180380-fec457a2-ae2d-4edc-8e14-c71170ea8446.png)
When I changed the _has_snippet_ into _true_,
![image](https://user-images.githubusercontent.com/45872450/151180751-cb3d2845-3fcc-4413-8b1b-9fb6d5abf5da.png)
I saw this in preview:
![image](https://user-images.githubusercontent.com/45872450/151180783-3a513ad2-5d38-4f60-93dc-5d7cbf9e23fc.png)
But  after saving the post, It seems that nothing has changed:
![image](https://user-images.githubusercontent.com/45872450/151181020-2b1257cb-f92f-4314-a1fe-b01f532d0b10.png)

--------

2. Next, I uploaded a shorter(3 lines) file and this happened:
![image](https://user-images.githubusercontent.com/45872450/151181752-08b83983-4fdc-4469-881b-6c0ddbbf5dd9.png)
After I click the button, nothing happens except the button text changes.
![image](https://user-images.githubusercontent.com/45872450/151181971-1e9f83f2-13dd-44d0-8678-ecc870a2d00a.png)

**Comment by krodelabestiole** [comment]
Hi, I face the same issue.

I get this message in the HTML code (div class _FofUpload-TextPreviewError_) :
```Error previewing file. It may have been deleted, or the provided file ID is invalid.```
It might not be related however since this div is not visible...

Here's an example : https://ufr-forum.crachecode.net/d/2062897-test-transfets-de-fichiers/12

The JavaScript still retrieves the link to the file : https://ufr-forum.crachecode.net/assets/files/2023-02-22/1677049996-661418-code.txt

This forum is a bit modified version of flarum but I have the same issue with a brand new one, using crazymax/flarum:latest

flarum v 1.6.2
fof/upload v 1.2.3
(in both cases)

Any help would be much appreciated !

**Comment by krodelabestiole** [comment]
ok I've got it ! (at least in my case)

The whole topic content is inside a _noscript_ tag :
```<noscript id="flarum-content">```

thus the inline `<script>` written just after the uploaded text preview won't be executed !

I guess it's a security method. I wonder how we could fix that not putting the website users at risk.
